In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier

In [2]:
df = pd.read_csv("processed_train_datav2.csv")

In [3]:
X = df.drop(['A_chosen', 'B_chosen', 'C_chosen', 'D_chosen', 
                 'E_chosen', 'F_chosen','G_chosen', 'chosen_match_final'], axis = 1)
y = df['A_chosen']

In [4]:
X.head()

Unnamed: 0  customer_ID  num_quotes  location  group_size  homeowner  \
0           0     10000000           8     10001           2          0   
1           1     10000005           5     10006           1          0   
2           2     10000007           7     10008           1          0   
3           3     10000013           3     10014           2          1   
4           4     10000014           5     10015           1          0   

   car_age  car_value  risk_factor  age_oldest    ...     state_OR  state_PA  \
0        2          7          3.0          46    ...            0         0   
1       10          5          4.0          28    ...            0         0   
2       11          3          3.0          43    ...            0         1   
3        3          4          3.0          62    ...            0         0   
4        5          4          3.0          32    ...            0         0   

   state_RI  state_SD  state_TN  state_UT  state_WA  state_WI  state_WV  \
0         0         0         0         0         0         0         0   
1         0         0         0         0         0         0         0   
2         0         0         0         0         0         0         0   
3         0         0         0         0         0         0         1   
4         0         0         0         0         0         0         0   

   state_WY  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 89 columns]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=32)

In [5]:
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)
log_predictions = logmodel.predict(X_test)

rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf_predictions = rf.predict(X_test)

mlp = MLPClassifier()
mlp.fit(X_train, y_train)
mlp_predictions = mlp.predict(X_test)

In [6]:
print(confusion_matrix(y_test,log_predictions))
print(classification_report(y_test,log_predictions))

[[    0  7146     0]
 [    0 19592     0]
 [    0  5275     0]]
             precision    recall  f1-score   support

          0       0.00      0.00      0.00      7146
          1       0.61      1.00      0.76     19592
          2       0.00      0.00      0.00      5275

avg / total       0.37      0.61      0.46     32013



/Users/peter/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [7]:
print(confusion_matrix(y_test,rf_predictions))
print(classification_report(y_test,rf_predictions))

[[ 6595   420   131]
 [  356 18788   448]
 [  101   702  4472]]
             precision    recall  f1-score   support

          0       0.94      0.92      0.93      7146
          1       0.94      0.96      0.95     19592
          2       0.89      0.85      0.87      5275

avg / total       0.93      0.93      0.93     32013



In [8]:
print(confusion_matrix(y_test,mlp_predictions))
print(classification_report(y_test,mlp_predictions))

[[ 7146     0     0]
 [19592     0     0]
 [ 5275     0     0]]
             precision    recall  f1-score   support

          0       0.22      1.00      0.36      7146
          1       0.00      0.00      0.00     19592
          2       0.00      0.00      0.00      5275

avg / total       0.05      0.22      0.08     32013



/Users/peter/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [9]:
import pickle

In [10]:
pickle.dump(rf, open('A_pred_rf_model.txt', 'wb'))